### ISSUE TITLE
exchange config.yml

### ISSUE THREAD

**Issue by eli-yamada** [eli-yamada/aws-sessionstore-dynamodb-ruby#2]
```
default: &default
  table_name: "sessions"
  table_key: "session_id"
  user_key: nil
  consistent_read: true
  read_capacity: 10
  write_capacity: 5
  raise_errors: false
  max_age: 7*3600*24
  max_stale: 3600*5
  enable_locking: false
  lock_expiry_time: 500
  lock_retry_delay: 500
  lock_max_wait_time: 1
  secret_key: nil
  verbose: false
  local_mode: false
  local_endpoint: "http://localhost:8000"

development:
  <<: *default
  region: 'ap-northeast-1'
  access_key_id: 'hoge'
  seacret_access_key: 'hoge3'
```
